### ISSUE TITLE
Admin shows old versions again after toggling menu back and forth

### ISSUE THREAD

**Issue by klausiob** [ioBroker/ioBroker.admin#1385]
If I update some Adapters the page shows immedently the new versions.
If I then click on Overview in the left menu and go back to Adapters, it shows the old versions again. 

 - Adapter version: Admin 5.2.3
 - JS-Controller version:  3.3.22
 - Node version: v14.18.1
 - Operating system: linux on Raspi

**Comment by Feuer-sturm** [comment]
@klausiob please verify your issue with current stable Version 5.3.1

**Comment by klausiob** [comment]
same error

**Comment by klausiob** [comment]
Sorry, false button

**Comment by Feuer-sturm** [comment]
I have the same issue with admin 5.3.2 as well.
It seems to be a refreshing issue. After refreshing the complete site everything is fine.

**Comment by klausiob** [comment]
I thought is the same error as with VIS in the web adapter. Please refer
https://github.com/ioBroker/ioBroker.web/issues/180

**Comment by GermanBluefox** [comment]
> I thought is the same error as with VIS in the web adapter. Please refer [ioBroker/ioBroker.web#180](https://github.com/ioBroker/ioBroker.web/issues/180)

These errors have nothing common...

**Comment by Feuer-sturm** [comment]
Issue is still there with Admin 6.0.2

**Comment by GermanBluefox** [comment]
Fixed in 6.0.6

**Comment by Feuer-sturm** [comment]
Tested with Admin 6.0.6 but on my system this issue is not fixed. The problem is still there.

**Comment by GermanBluefox** [comment]
PLease retry with 6.0.7

**Comment by Feuer-sturm** [comment]
Is fixed in 6.0.7
