### ISSUE TITLE
[v3] Config dialogs don't scroll in Firefox => save bar hidden

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#146]
See picture:
![no-scrolling](https://user-images.githubusercontent.com/17641229/35480938-ff9ffb58-0419-11e8-8b46-52ddf8a92b62.PNG)

**Comment by GermanBluefox** [comment]
Fixed in 3.1.3

**Comment by AlCalzone** [comment]
It's better in 3.1.4:
![unbenannt](https://user-images.githubusercontent.com/17641229/35483987-3933203c-0449-11e8-950c-dcb009f40b81.PNG)
but still not perfect. I should **not** be able to scroll here, as the content is smaller than the container.

**Comment by Apollon77** [comment]
Noticed it too. No scroll für custom dialog and also edit-object dialog. Partially also the adapter config dialogs. So basically all overlay style Dialogs affected.

**Comment by GermanBluefox** [comment]
Please retest with 3.1.5

**Comment by AlCalzone** [comment]
Fixed for me
