### ISSUE TITLE
Admin 6: jsonConfig - linkeddevices: editing existing linked object -> input fields are not filled

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.admin#1658]
**Describe the bug**  
Editing a still existing linked object dont show input in for _prefixId and _stateId.

**To Reproduce**  
take a look on the attached animated gif image, this shows the behaviour

![jsonCustomBug_2](https://user-images.githubusercontent.com/6370451/186403372-ee90dc5c-c048-44ad-8277-147adb1d2c70.gif)

**Expected behavior**  
input field should be field from linkedId property

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 6.2.17
 - JS-Controller version: 4.0.23
 - Node version: 16.17.0
 - Operating system: ubuntu

**Additional context**  
https://github.com/Scrounger/ioBroker.linkeddevices/issues/84

I dont know if this is a bug from Admin 6 site or a problem of my jsonCustom file.
https://github.com/Scrounger/ioBroker.linkeddevices/blob/master/admin/jsonCustom.json

**Comment by Scrounger** [comment]
I have tested it. 

![grafik](https://user-images.githubusercontent.com/6370451/186452898-5a6ad2e3-663c-4d36-aee3-8817f655b47d.png)

_stateId is not taken from `data.linkedId`, it takes the last part of the object id.

```
                "_stateId": {
                    "type": "autocompleteSendTo",
                    "label": "id of linked object",
                    "sm": 4,
                    "noMultiEdit": true,
                    "freeSolo": true,
                    "noTranslation": true,
                    "command": "suggestions_stateId",
                    "maxLength": 255,
                    "defaultFunc": {
                        "func": "(data.linkedId || '').split('.').pop()",
                        "alsoDependsOn": [
                            "linkedId"
                        ]
                    },
                    "validator": "data._stateId && data._stateId.length > 0 && !(/[*?\"'`´,;:<>#/{}ß\\[\\]\\s]/).test(data._stateId)",
                    "help": "${data._stateId && data._stateId.length > 0 && !(/[*?\"'`´,;:<>#/{}ß\\[\\]\\s]/).test(data._stateId) ? '' : 'please enter a valid id, the following chars are not allowed \\'*?\"\\'`´,;:<>#/{}ß[] \\''}"
                },
```

**Comment by GermanBluefox** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/4582016/187266598-ddc769e3-684c-4752-bf6e-db0d63eecf0f.png)

**Comment by Scrounger** [comment]
i tested 6.2.21. 
Unfortunately, it still does not work.  Now also the '_prefixId' in the input field does not work anymore.

![grafik](https://user-images.githubusercontent.com/6370451/188583171-a2be2e08-ec5b-4c21-80e6-9636f52242d7.png)

**Comment by foxriver76** [comment]
So no longer admin bug and will be fixed in adapter @GermanBluefox?
