### ISSUE TITLE
GUI error 

### ISSUE THREAD

**Issue by merlinfive** [ioBroker/ioBroker.admin#2112]
instrument.ts:124 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisDocker%2C%20isOfficial%2C%20officialVersion%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zr (react-dom.production.min.js:152:60)
    at h (react-dom.production.min.js:156:186)
    at S (react-dom.production.min.js:158:331)
    at Q (react-dom.production.min.js:162:334)
    at ae (react-dom.production.min.js:192:308)
    at oa (react-dom.production.min.js:294:9)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:124

**Comment by Feuer-sturm** [comment]
@merlinfive Which admin version is installed? What did you do to trigger the error?

**Comment by FranticMan** [comment]
I am using Versin 6.8.0

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisDocker%2C%20isOfficial%2C%20officialVersion%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 13
[instrument.ts:132](http://ds220plus:8081/static/node_modules/@sentry/src/instrument.ts)
    je instrument.ts:132
    React 11

**Comment by Feuer-sturm** [comment]
@FranticMan What did you do to trigger the error?

**Comment by FranticMan** [comment]
> @FranticMan What did you do to trigger the error?

At the intro tab I have pressed the info button of the admin card.

**Comment by superemil70** [comment]
Ich habe das gleiche Problem und Meldung wie @FranticMan seit update gestern.
Adapter sind alle auf dem neusten Stand. Habe es im Forum aucch geschrieben
https://forum.iobroker.net/post/1044199

**Comment by foxriver76** [comment]
6.10.1 will be stable the next days and should fix this problem

**Comment by winnyschuster** [comment]
> 6.10.1 will be stable the next days and should fix this problem

i have 6.10.1 installed and error still occurs. For me this seems related to the now solved issue we recently had with Docker and the hosts tab. Here error occurs when clicking info Tab
![Info](https://github.com/ioBroker/ioBroker.admin/assets/7774086/f54b279b-b6df-41a5-a6e8-5fcdf8de0639)

**Comment by foxriver76** [comment]
@winnyschuster can you show me the browser console error with 6.10.1

**Comment by winnyschuster** [comment]
18:29:34.500 bootstrap.jsx:20 iobroker.admin@6.10.1
18:29:34.512 sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.68.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
18:29:34.571 instrument.ts:144 [2023-09-17T16:29:34.569Z] Try to connect
18:29:34.617 instrument.ts:144 Stored version: , new version: 6.10.1
18:29:34.667 instrument.ts:144 Connected: true
18:29:37.426 instrument.ts:144 Double links: "flot.0/flot/edit.html" and "flot.0"
18:29:37.450 instrument.ts:144 Translate: Link
18:29:38.044 instrument.ts:144 Translate: time
18:29:38.044 instrument.ts:144 Translate: timeOffset
18:29:38.044 instrument.ts:144 Translate: dockerInformation
18:29:38.044 instrument.ts:144 Translate: _nodeCurrent
18:29:38.044 instrument.ts:144 Translate: _nodeNewest
18:29:38.044 instrument.ts:144 Translate: _nodeNewestNext
18:29:38.044 instrument.ts:144 Translate: _npmCurrent
18:29:38.045 instrument.ts:144 Translate: _npmNewest
18:29:38.045 instrument.ts:144 Translate: _npmNewestNext
18:30:23.590 sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.68.0:1     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
18:53:07.737 instrument.ts:144 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisDocker%2C%20isOfficial%2C%20officialVersion%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ka (react-dom.production.min.js:152:60)
    at d (react-dom.production.min.js:156:186)
    at h (react-dom.production.min.js:158:331)
    at e (react-dom.production.min.js:162:334)
    at wo (react-dom.production.min.js:192:308)
    at Ei (react-dom.production.min.js:294:9)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at ss (react-dom.production.min.js:273:300)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonym) @ instrument.ts:144
18:53:29.201 fetch.ts:45     POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.68.0 net::ERR_BLOCKED_BY_CLIENT
(anonym) @ fetch.ts:45
(anonym) @ base.ts:76
add @ promisebuffer.ts:49
i @ base.ts:92
value @ baseclient.ts:713
value @ client.ts:138
(anonym) @ client.ts:69
18:53:29.205 fetch.ts:45 Abrufen konnte nicht geladen werden: POST „https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.68.0“.
(anonym) @ fetch.ts:45
(anonym) @ base.ts:76
add @ promisebuffer.ts:49
i @ base.ts:92
value @ baseclient.ts:713
value @ client.ts:138
(anonym) @ client.ts:69


sorry, seems hard to get well formed output in chrome

**Comment by winnyschuster** [comment]
> @winnyschuster can you show me the browser console error with 6.10.1

an additional obseravation: When first going to the hosts tab and clicking on hostname, platform property shows like `docker - official image........`. Going from there to overview tab, the platform property shows the same as in hosts tab. There will be **no error when clicking the info button then.**

If i refresh browser from there, platform property only shows **docker** and when clicking info button again the error occurs as described.

Hope that helps, there seem to be two different functions to be used when determining docker environment
