### ISSUE TITLE
[bug]: Login with password manager no longer possible

### ISSUE THREAD

**Issue by UncleSamSwiss** [ioBroker/ioBroker.admin#3047]
### No existing issues.

- [x] There is no existing issue for my problem.

### Describe the bug

This bug happens after the update to version 7.6.3

I'm using 1password in Chrome and when I try to log in using the auto-fill functionality, the login doesn't work. It works if I copy the password from the password manager and enter it manually.

Looking at the network log of the developer tools, I can see the `/oauth/token` and the `/login?href=` requests being started at the exact same time. When it works (i.e. when manually copying the password), the requests are about 500ms apart.

I believe the problem lies in the fact that the password manager clicks the "Log in" button automatically which has some weird effect on timing and then the "redirect" request is executed at the same time as the "token" request which ends up with the "redirect" request not containing the token.

**Note:** After some more testing, I figured out that the user is actually logged in, but the login page is shown instead of redirecting to the admin intro tab. This seems related to #2997

### To Reproduce

1. Open ioBroker admin page in Chrome
2. Click in the "Login name" field
3. Select the proposed login from the password manager
4. The password manager will automatically fill the login name and password **and clicks the "Log in" button**
5. You will be redirected to the login page

### Expected behavior

Log in with a password manager that performs auto-fill is supported.

### Screenshots & Logfiles

Failing login with auto-fill:
![Image](https://github.com/user-attachments/assets/5e0ea099-7cb0-4be4-9854-12e745a456bd)

Successful login with manual password entry:
![Image](https://github.com/user-attachments/assets/d1fcc4ed-5478-4dc5-9c44-c34700259121)

### Adapter version

7.6.3

### js-controller version

6.0.11

### Node version

18.20.2

### Operating system

Linux / Docker

**Comment by bjoernbusch** [comment]
Reproducible also with 7.6.4.

**Comment by mcm1957** [comment]
fixed with 7.6.5

**Comment by bjoernbusch** [comment]
I hate to report that I can still reproduce it with 7.6.5. 🙈 I'm on Firefox with 1Password and I cleaned and reloaded the page multiple times and disabled the cache to be really sure that the latest stuff is loaded, but after submitting the credentials via 1Password I get again redirected to the login page (:8081/index.html?login&href=%2Flogin%3Fhref%3D). When I manually submit it it works fine.

**Comment by bjoernbusch** [comment]
I've updated to 7.6.6., cleaned all caches, etc. When I log in manually, everything is working perfectly. When I log in via 1Password with autosubmit, I do get logged in and I'm also forwarded to the intro tab, but the URL now contains the login dialog information:

`:8081/index.html?username=admin&password=mySuperSecretPassword&stayloggedin=on&origin=%2Findex.html%3Flogin#tab-intro`

when I navigate to different pages, that information stays in the URL.

`:8081/index.html?username=admin&password=mySuperSecretPassword&stayloggedin=on&origin=%2Findex.html%3Flogin#tab-objects`

If I can be of any more help, test any changes locally, let me know.

**Comment by BerziOnline** [comment]
> I've updated to 7.6.6., cleaned all caches, etc. When I log in manually, everything is working perfectly. When I log in via 1Password with autosubmit, I do get logged in and I'm also forwarded to the intro tab, but the URL now contains the login dialog information:
> 
> `:8081/index.html?username=admin&password=mySuperSecretPassword&stayloggedin=on&origin=%2Findex.html%3Flogin#tab-intro`
> 
> when I navigate to different pages, that information stays in the URL.
> 
> `:8081/index.html?username=admin&password=mySuperSecretPassword&stayloggedin=on&origin=%2Findex.html%3Flogin#tab-objects`
> 
> If I can be of any more help, test any changes locally, let me know.

I can confirm that. Login is working now with password-managers, but alle credentials are in clear text within the URL.

**Comment by mcm1957** [comment]
@GermanBluefox 
I've removed 'fixed' as the url showing the crendentials should be fixed.

**Comment by GermanBluefox** [comment]
> I've updated to 7.6.6., cleaned all caches, etc. When I log in manually, everything is working perfectly. When I log in via 1Password with autosubmit, I do get logged in and I'm also forwarded to the intro tab, but the URL now contains the login dialog information:
> 
> `:8081/index.html?username=admin&password=mySuperSecretPassword&stayloggedin=on&origin=%2Findex.html%3Flogin#tab-intro`
> 
> when I navigate to different pages, that information stays in the URL.
> 
> `:8081/index.html?username=admin&password=mySuperSecretPassword&stayloggedin=on&origin=%2Findex.html%3Flogin#tab-objects`
> 
> If I can be of any more help, test any changes locally, let me know.

Hm... such a behavior comes from 1password. It tries to  guess which method will be used for authentication and it guesses wrong. So in this case only the 1password is guilty. But I tried to cheat the 1passowrd in 7.6.7

**Comment by BerziOnline** [comment]
> > I've updated to 7.6.6., cleaned all caches, etc. When I log in manually, everything is working perfectly. When I log in via 1Password with autosubmit, I do get logged in and I'm also forwarded to the intro tab, but the URL now contains the login dialog information:
> > `:8081/index.html?username=admin&password=mySuperSecretPassword&stayloggedin=on&origin=%2Findex.html%3Flogin#tab-intro`
> > when I navigate to different pages, that information stays in the URL.
> > `:8081/index.html?username=admin&password=mySuperSecretPassword&stayloggedin=on&origin=%2Findex.html%3Flogin#tab-objects`
> > If I can be of any more help, test any changes locally, let me know.
> 
> Hm... such a behavior comes from 1password. It tries to guess which method will be used for authentication and it guesses wrong. So in this case only the 1password is guilty. But I tried to cheat the 1passowrd in 7.6.7

I am using nextcloud password manager and it has the same behaviour. And it does that just in iobroker, really nowhere else.

**Comment by BerziOnline** [comment]
> 7.6.7. looks really good, both manual and automatic login are working perfectly with Firefox and 1Password. Thanks for looking into this!

Problem of the cleartext credentials inside the URL is solved here as well. Just the auto fill from the password manager doesn't work for the username since this version anymore. If you choose to fill out the credentials just the password is filled in - the method doesn't matter. 

So while solving this issue here, something has been changed what avoids to fill out the username line by password managers (at least from Nextcloud). This has not been the case with versions before 7.6.7.
