### ISSUE TITLE
Menu Dateien - Deleting of folders does not work well

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#812]
Admin 5.0.12
js-controller 3.3.5

Problem found during testing this issue https://github.com/ioBroker/ioBroker.admin/issues/779

There are problems with deleting folders

A few minutes I created a folder temp und currently there is no content in this folder in the UI. If I click the delete button the following error will be prompted in the browser console
![grafik](https://user-images.githubusercontent.com/25422320/116823355-5715a080-ab84-11eb-89b3-f66d19946a3c.png)
![grafik](https://user-images.githubusercontent.com/25422320/116823311-000fcb80-ab84-11eb-93f8-694229e77b7b.png)

If I have a look in the folder structure in vis.0 my previous created tempmytemp and "temp ordner" folders are still there and in the "temp" folder which makes the problem in the UI there is a subfolder.
![grafik](https://user-images.githubusercontent.com/25422320/116823426-c25f7280-ab84-11eb-8a7b-8730ca9404fe.png)

![grafik](https://user-images.githubusercontent.com/25422320/116823503-3863d980-ab85-11eb-9d32-92ae49259242.png)

Steps to reproduce:
- create a folder "tempNew"
- upload an image in this new folder
- press delete icon of the folder
-- icon in the folder will be deleted
-- folder will stay but delete icon is not available any more
- press button "Dateien neue laden" in the React UI
- folder "tempNew" will not be shown in the UI but it is still there on the disc

**Comment by GermanBluefox** [comment]
Fixed in 5.0.13

**Comment by Feuer-sturm** [comment]
Admin 5.0.13
js-controller 3.3.6

@GermanBluefox I am sorry to tell that it is not fixed.

Steps to reproduce
- create folder "temp123"
- upload image in "temp123"
- delete folder "temp123"

Folder "temp123" is not any more visible in React UI -> ok
Folder is still available on the disc. Folder is empty.
![grafik](https://user-images.githubusercontent.com/25422320/116827917-f09c7c80-ab9b-11eb-9bb6-34f8db5fddac.png)

**Comment by GermanBluefox** [comment]
Ok. I tested only redis, as redis does not have folders on disk, as it does not have disk.

**Comment by GermanBluefox** [comment]
Please try 5.0.15

**Comment by Feuer-sturm** [comment]
Is fixed with 5.0.15 :-)
